In [1]:
# NumPy Creating Arrays
# Create a NumPy ndarray Object
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
# Dimensions in Arrays
import numpy as np

# 0-D Arrays
arr = np.array(12)
print(arr)
print(type(arr))

12
<class 'numpy.ndarray'>


In [3]:
# 1-D Arrays
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
# 2-D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [9]:
# 3-D Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)
print(type(arr))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>


In [15]:
# Check Numbers of Dimensions?
import numpy as np

a = np.array(12)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1 ,2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [18]:
# Higher Dimensional Arrays
import numpy as np

arr = np.array([1, 2, 3], ndmin=5)
print(arr)
print('Number of dimensions: ', arr.ndim)

[[[[[1 2 3]]]]]
Number of dimensions:  5
