In [1]:
# NumPy Data Types
# Data Types in Python
# Checking the Data Type of an Array
# Get the data type of an array object:
import numpy as np

arr = np.array([1,2,3,4])
print(arr.dtype)

int32


In [2]:
# Get the data type of an array containing strings:
import numpy as np

arr = np.array(['apple', 'banana', 'strawberry'])
print(arr.dtype)

<U10


In [3]:
# Creating Arrays With a Defined Data Type
# Create an array with data type string:
import numpy as np

arr = np.array([1,2,3,4,5], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [4]:
# Create an array with data type 4 bytes integer:
import numpy as np

arr = np.array([1,2,3,4,5], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [12]:
# Converting Data Type on Existing Arrays
# Change data type from float to integer by using 'i' as parameter value:
import numpy as np

arr = np.array([2.3, 4.6, 1.2])

newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[2 4 1]
int32


In [15]:
# Change data type from float to integer by using int as parameter value:
import numpy as np

arr = np.array([1.2, 5.6, 3.4])

newarr = arr.astype('int')

print(newarr.dtype)
print(newarr)

int32
[1 5 3]


In [20]:
# Change data type from integer to boolean:
import numpy as np

arr = np.array([1, -8, 2, 0])

newarr = arr.astype('bool')

print(newarr)
print(newarr.dtype)

[ True  True  True False]
bool
