In [1]:
# NumPy Array Copy vs View
# COPY:
# Make a copy, change the original array, and display both arrays:
import numpy as np

arr = np.array([1,2,3,4,5])

i = arr.copy()
arr[1] = 8

print(arr)
print(i)

[1 8 3 4 5]
[1 2 3 4 5]


In [2]:
# VIEW
# Make a view, change the original array, and display both arrays:
import numpy as np

arr = np.array([1,2,3,4,5])
i = arr.view()

arr[0] = 7

print(arr)
print(i)

[7 2 3 4 5]
[7 2 3 4 5]


In [3]:
# Make Changes in the VIEW:
# Make a view, change the view, and display both arrays:
import numpy as np

arr = np.array([1,2,3,4,5])

i = arr.view()
i[0] = 30

print(arr)
print(i)

[30  2  3  4  5]
[30  2  3  4  5]


In [5]:
# Check if Array Owns it's Data
# Print the value of the base attribute to check if an array owns it's 
import numpy as np

arr = np.array([1,2,3,4,5,6])

a = arr.copy()
b = arr.view()

print(a.base)
print(b.base)

None
[1 2 3 4 5 6]
