In [5]:
# NumPy Array Reshaping
# Reshape From 1-D to 2-D
# Convert the following 1-D array with 12 elements into a 2-D array.
# The outermost dimension will have 4 arrays, each with 3 elements:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(4, 3)

print('Origial array: ', arr)
print('Reshaped array: ', newarr)

Origial array:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array:  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
# Reshape From 1-D to 3-D
# Convert the following 1-D array with 12 elements into a 3-D array.
# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(2, 3, 2)

print('Original array: ', arr)
print('Reshape array: ', newarr)

Original array:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshape array:  [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [14]:
# Returns Copy or View?
# Check if the returned array is a copy or a view:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

newarr = arr.reshape(2, 4)

print(newarr)
print(newarr.base)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [21]:
# Unknown Dimension
# Convert 1D array with 8 elements to 3D array with 2x2 elements:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
# Flattening the arrays
# Convert the array into a 1D array:
import numpy as np

arrA = np.array([[1,2,3], [4,5,6]])
arrB = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

newarrA = arrA.reshape(-1)
newarrB = arrB.flatten()

print(newarrA)
print(newarrB)

[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
